# Generated by Django 4.1.3 on 2022-11-13 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vin', models.CharField(max_length=6)),
                ('mileage', models.IntegerField()),
                ('service_type', models.CharField(choices=[('M', 'Maintenance'), ('MA', 'Major Repair'), ('C', 'Collision'), ('P', 'Parts'), ('T', 'Tires')], default='M', max_length=15)),
                ('description', models.TextField(max_length=10000)),
                ('invoice_total', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.car')),
            ],
        ),
    ]
