# Generated by Django 4.1.3 on 2022-11-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateField(verbose_name='Maintenance Date'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='invoice_total',
            field=models.CharField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='mileage',
            field=models.CharField(max_length=1000000),
        ),
    ]
