# Generated by Django 4.1.3 on 2022-11-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rentals',
            field=models.ManyToManyField(to='main_app.rental'),
        ),
    ]
